version: '3.4'

services:
  redis:
    container_name: "Redis"
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: "Calculator"
    build: ./src
    environment:
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0

    ports:
      - "8080:8080"
